config/routes.rb
Rails.application.routes.draw do

   resources :admin do
     get 'add_admin_or_remove_admin' , :on => :collection
   end
   patch 'admin/update/:id' => 'admin#update'
   get 'users/show/:id' => 'users#show',as: :show_user,:id=>/\d+/
   get 'users/edit/:id'  => 'users#edit', as: :edit_user,:id=>/\d+/
   get 'users/change_password/:id' => 'users#change_password',as: :change_password,:id=>/\d+/
   post 'users/update/:id' => 'users#update'
   post 'users/update_password/:id' => 'users#update_password',as: :update_password,:id=>/\d+/
   get 'login/logout/:id' => 'login#logout',as: :logout
   post 'login/verify_login'

   root 'login#login'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  def self.create_user(user_params)
    user = self.new(user_params)
    user.save
  end

  def update_user(user_params)
    self.update(user_params)
  end

  def update_password(password)
    self.update_attributes(:password => password)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_filter :check_session
  before_filter :admin_session
  def new
    @user = User.new
  end

  def create
    @user = User.create_user(user_params)

    if @user
      redirect_to admin_index_path
      if params[:user][:admin]
      flash[:notice] = "Admin creates a user and given admin access"
      else
        flash[:notice] = "normal user created by admin successfully"
      end
    else
      redirect_to :action => 'new'
    end
  end

  def edit
      @user = User.find_by_id(params[:id])
      if @user.blank?
        redirect_to root_path
        flash[:notice] = "No user Present"
      end
  end

  def update
    @user = User.find_by_id(params[:id])
    if !@user.blank?
      admin_value = @user.admin
      @user.update_user(user_params)
      redirect_to admin_index_path
      if params[:user][:admin] == "1" and admin_value == false
        flash[:notice] = "User is upgraded from Normal user to admin"
      elsif params[:user][:admin] == "0" and admin_value == true
        flash[:notice] = "User is downgraded from Admin to Normal User"
      else
      flash[:notice] = "Updated Succesfully"
      end
    else
      render 'edit'
    end
  end


  def show
    @user = User.find_by_id(params[:id])
    if  @user.blank?
      redirect_to root_path
      flash[:notice] = "No user Present"
    end
  end

  def index
    @users = User.all
  end

  def destroy
      @user = User.find(params[:id])
      @user.destroy
      flash[:notice] = "User Deleted Successfully"
    redirect_to admin_index_path
  end

  def add_admin_or_remove_admin
    debugger
    @user = User.find(params[:user_id])
    if @user.admin == true
      @user.update_attributes(:admin => false)
      render :text => "Add Admin"
    else
      @user.update_attributes(:admin => true)
      render :text => "Remove Admin"
    end

  end

  private
  def user_params
      params.require(:user).permit(:name,:password,:email,:description,:admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def check_session
    if !session[:user_id].blank?
      user = User.find_by_id(session[:user_id])
     if user.id != session[:user_id]
      redirect_to root_path
      flash[:notice] = "No user Present"
     end
    else
      redirect_to root_path
      flash[:notice] = "Login First"
    end
  end


  def admin_session
    if session[:role]
      user = User.find_by_id(session[:user_id])
      if user.blank?
      redirect_to root_path
      flash[:notice] = "No user Present"
      end
      else
      redirect_to root_path
      flash[:notice] = "you are not admin"
    end
  end


end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_filter :check_session,:except => [:login,:verify_login]


  def login

  end

  def verify_login

    @user = User.where("email =? and password =?",params[:email],params[:password]).last
    if !@user.blank?
      if @user.admin == true
         redirect_to admin_index_path
        session[:user_id] = @user.id
         session[:role] = @user.admin
         flash[:notice] = "Logged in as Administrator, you can edit , view and modify others profile"
      else
        session[:user_id] = @user.id
        redirect_to show_user_path(session[:user_id])
        flash[:notice] = "Logged in as #{@user.name},you can only view and edit profile of yours"
      end
    else
      flash[:notice] = "No User"
      redirect_to :action => 'login'
    end

  end

  def no_method
     render 404
  end

  def logout
    reset_session
    redirect_to :action => 'login'
    flash[:notice] = "logged out successfully"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

     before_filter :check_session

  def edit
    @user = User.find_by_id(params[:id])
    if  !@user.blank?
     if session[:user_id] == params[:id].to_i
    else
    redirect_to root_path
    flash[:notice] = "you are not authorised to edit others profile"
    end
    else
    flash[:notice] = "No User Present"
    redirect_to root_path
    end
  end

   def update
     @user = User.find_by_id(params[:id])
     if !@user.blank?
       @user.update_user(user_params)
       if session[:user_id] == @user.id
       flash[:notice] = "Succesfully updated"
       redirect_to show_user_path
       end
     else
       flash[:notice] = "No Proper User Data to update"
       redirect_to root_path
      end
   end


  def show
    @user = User.find_by_id(params[:id])
    if  !@user.blank?
      if session[:user_id] == @user.id
      else
        redirect_to root_path
        flash[:notice] = "You are not authorised or normal user to view Profile"
      end
    else
      redirect_to root_path
        flash[:notice] = "No user Present"
    end
  end

   def change_password
     @user = User.find_by_id(params[:id])
     if  !@user.blank?
       if session[:user_id] != @user.id

         redirect_to root_path
         flash[:notice] = "You are not authorised or update users password"
       end
     else
       redirect_to root_path
       flash[:notice] = "No user Present"
     end

   end

     def update_password

       @user = User.find_by_id(params[:id])
       if  !@user.blank?
         if session[:user_id] != @user.id
           redirect_to root_path
           flash[:notice] = "You are not authorised to update users password"
         elsif @user.password == params[:exist_password]
             if params[:new_password] == params[:confirm_password]
               @user.update_password(params[:new_password])
                   flash[:notice] = "Password updated succesfully"
               redirect_to show_user_path
             else
               flash[:notice] = "new password and confirm password is not matching"
               redirect_to change_password_path
             end
           else
             flash[:notice] = "old password is not matching"
             redirect_to change_password_path
             end
       else
         redirect_to root_path
         flash[:notice] = "No user Present"
       end

     end


  private
  def user_params
      params.require(:user).permit(:name,:password,:email,:description)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_form.html.erb
<style>
  .red{
    color : red;
  }

</style>
<div class="red">
  <%= flash[:notice] if flash[:notice] %>
</div>
<%= form_for  @user ,  url: { action: "create" }, method: :post do |f|  %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>
    <% if session[:role] %>
        <p>
          <%= f.label :admin %><br>
          <%= f.check_box :admin %>
        </p>
     <% end %>
    <p>
      <%= f.submit %>
    </p>

<% end %>

<%= link_to 'Log out', logout_path(session[:user_id]) %>|
<%= link_to 'Change Password', logout_path(session[:user_id]) %>

app/views/admin/edit.html.erb
<h1>Edit</h1>
<%#= render 'form' %>

<%= form_for  @user ,:url => "/admin/update/#{params[:id]}"  do |f|  %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>
    <p>

    <%= f.label :password %>
    <%= f.password_field :password  ,:value => @user.password %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>
    <% if session[:role] %>
        <p>
          <%= f.label :admin %><br>
          <%= f.check_box :admin %>
        </p>
    <% end %>
    <p>
      <%= f.submit %>
    </p>

<% end %>
<%= link_to 'Log out', logout_path(session[:user_id]) %> |
<%= link_to 'Back', admin_index_path %>

app/views/admin/index.html.erb
<style>
  .red{
    color : red;
  }
    .password{
      display:none;
    }
</style>
<h1>Users List</h1>
<div class="red">
  <%= flash[:notice] if flash[:notice] %>
</div>
<table>
  <% if !@users.blank? %>
      <% @users.each do |user|  %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= link_to 'Show', admin_path(user) %></td>
            <td><%= link_to 'Edit', edit_admin_path(user) %></td>
            <td><%= link_to 'Destroy', admin_path(user),
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %></td>
            <td>
              <%= link_to user.admin ? "Admin" : "User" ,'javascript:;'%>
              <%#= link_to user.admin ? "Remove Admin" : "Add Admin" ,'javascript:;', class: "admin_make" ,value:user.id%></td>
            <!--<td><%#= link_to 'change password' ,'javascript:;' , class: "change_password", value:user.id %><%#= text_field "pass" , "" ,class: "password"%></td>-->

          </tr>
      <% end %>
  <% end %>
</table>

<%= link_to 'New user', new_admin_path %> |
<%= link_to 'Log out', logout_path(session[:user_id]) %>

<script>

  $('.admin_make').click(function(){

      var a = $(this).attr('value');
    var b = $(this).text();
      alert(a);
      alert(b);

        $.ajax({

          type: "GET",
          url: '/admin/add_admin_or_remove_admin?&user_id=' + a ,
          beforeSend: function (xhr) {
            xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
          },
          dataType : "html",
          success: function (data) {

          }
        });


  });

  $('.change_password').click(function() {

    $(this).hide();
    $(this).next('.password').show();
  });

  $('.password').change(function() {


    var a = $(this).val();
    var b = $(this).closest('.change_password').val();
    alert(a);
    alert(b);


//    $.ajax({
//
//      type: "GET",
//      url: '/admin/change_password?&user_id=' + a ,
//      beforeSend: function (xhr) {
//        xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
//      },
//      dataType : "html",
//      success: function (data) {
//
//
//      }
//    });
  });



</script>

app/views/admin/new.html.erb
<style>
  .red{
    color : red;
  }

</style>

<%= render 'form' %>
<%= link_to 'Back', admin_index_path %>

app/views/admin/show.html.erb
<style>
  .red{
    color : red;
  }
</style>

<h1>Show</h1>
<div class="red">
<%= flash[:notice] if flash[:notice] %>
 </div>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<!--<p>-->
  <!--<strong>Password:</strong>-->
  <!--<%#= @user.password %>-->
<!--</p>-->

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>

<%= link_to 'Edit', edit_admin_path(@user) %>|
<%= link_to 'Back', admin_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PracticeAppDeepak</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/login/404.html.erb
<h1>No routes</h1>

app/views/login/login.html.erb
<style>
  .red{
    color : red;
  }
</style>

<h1>Login</h1>
<div class="red">
<p><%= flash[:notice] if flash[:notice] %></p>
</div>
<%= form_tag('/login/verify_login') %>

<p>
  <%= label_tag("Email:") %>
  <%= text_field_tag(:email) %>
</p>

<p>
  <%= label_tag("password:") %>
  <%= password_field_tag(:password) %>
</p>

<p>
  <%= submit_tag 'login' %>
</p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>
    <% if session[:role] %>
        <p>
          <%= f.label :admin %><br>
          <%= f.check_box :admin %>
        </p>
     <% end %>
    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Log out', logout_path(session[:user_id]) %>

app/views/users/change_password.html.erb
<style>
  .red{
    color : red;
  }
  .password{
    display:none;
  }
</style>



<h1>Change Password</h1>

<div class="red">
  <%= flash[:notice] if flash[:notice] %>
</div>
<%= form_tag({:action => 'update_password'},{:method => :post})  do %>
    <p>
      <%= label_tag 'old_password' %>
      <%#= text_field_tag 'exist_password' %>
      <%= password_field_tag 'exist_password' %>



    </p>
    <p>
      <%= label_tag 'new_password' %>
      <%= password_field_tag 'new_password' %>
    </p>
    <p>
      <%= label_tag 'confirm_password' %>
      <%= password_field_tag 'confirm_password' %>
    </p>
    <%= submit_tag 'update_password'%>
<% end %>
<%= link_to 'Back', show_user_path(@user) %>|
<%= link_to 'Log out', logout_path(session[:user_id]) %>|

app/views/users/edit.html.erb
<h1>Edit</h1>
<%= form_for :user,url: { action: "update" } do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>
    <!--<p>-->
    <%#= f.label :password %>
    <!--<%#= f.password_field :password %>-->
    <!--</p>-->

    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>
    <p>
      <%= f.submit 'Update User' %>
    </p>

<% end %>

<%= link_to 'Back', show_user_path(@user) %>|
<%= link_to 'Log out', logout_path(session[:user_id]) %>|
<%= link_to 'Change Password', change_password_path(session[:user_id]) %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<style>
  .red{
    color : red;
  }
</style>

<h1>Show</h1>
<div class="red">
<%= flash[:notice] if flash[:notice] %>
 </div>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>
<% if @user.admin == true %>
<%= link_to 'Back', users_path %>
<% end %>